### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by eiais** [lichess-org/leroyjenkins#15]
leroyjenkins might not be the best name for a software project if one of the goals is to be inclusive. For a lot people that meme is linked with [racism and minstrel shows. ](https://wiihfellows.wordpress.com/2013/10/09/at-least-i-have-chicken-the-common-sense-comedy-of-leeerrrooyyyy-jennnnkinnss/)

**Comment by lakinwecker** [comment]
After considering the issue, we don't think the name needs to be changed due to the motivations of the person behind the original video, as we believe most if not all current references to the meme are in the sense of "taking decisive action without planning," which is certainly how we meant it.
