### ISSUE TITLE
Fix set existence test

### ISSUE THREAD

**Issue by lakinwecker** [lichess-org/leroyjenkins#4]
Undo this, but fix the existence test: https://github.com/lichess-org/leroyjenkins/commit/76591eec4e14e1f81c8b7079bab3063bb9ada865

**Comment by niklasf** [comment]
Upstream bug: https://github.com/lazytiger/ipset/pull/4

**Comment by lakinwecker** [comment]
Fixed by 9a707f193bf94b7917868ff71e14bb3fbb96f07e
